version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    env_file: .env
  web:
    build: .
    command: lein run
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
      - "${LEIN_REPL_PORT}:${LEIN_REPL_PORT}"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
