version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    env_file: .env
  web:
    build: .
    environment: &envs
      - PORT=${PORT}
      - CLJ_ENV=${CLJ_ENV}
      - DB_URL=${DB_URL}
    command: lein run
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
