# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    working_directory: app/
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      -run:
        name: Intstall dependencies
        command: |
          apk add --no-cache py-pip=9.0.0-r1
          pip install docker-compose==1.12.0
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "app/project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
        name: Load Docker image layer cache
        command: |
          set +o pipefail
          docker load -i /caches/app.tar | true
      - run:
        name: Build application Docker image
        command: |
          docker build --cache-from=app -t app .
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "app/project.clj" }}
      - run:
        name: Run tests
        command: |
          docker-compose run web lein test
